version: '3'
services:
  ott-mysql:
    container_name: ott-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: ott
      MYSQL_USER: agniya
      MYSQL_PASSWORD: Q1w2E3r4!
      MYSQL_ROOT_PASSWORD: Q1w2E3r4!
    ports:
      - "13306:3306"
    restart: always
    networks:
      - net

  ott:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - ott-mysql
    networks:
      - net
networks:
  net:
    driver: bridge